#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config window_gap 19
bspc config top_padding 61
bspc config split_ratio 0.5
bspc config normal_border_color "#363636"
bspc config focused_border_color "#8c8c8c"
bspc config presel_feedback_color "#8c8c8c"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc rule -a Screenkey manage=off
bspc rule -a Chromium desktop='^6'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^5'
bspc rule -a MPlayer state=floating
bspc rule -a GParted state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a love state=floating

hsetroot -solid "#7d7a85"
#nitrogen --restore &
picom &
$HOME/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
blueberry-tray &
xsettingsd & disown
