#!/bin/bash
#
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.


# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &

rfkill unblock all &

$HOME/.screenlayout/multihead.sh &

# Stop other wm's from screwing up
[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
      grep '^_NET_WM_NAME' | cut -d\" -f 2)
  }

if [[ $wm = "Openbox" ]]; then
nitrogen --restore &
picom &
xautolock -detectsleep -time 10 -locker "glock" \
-notify 30 \
-notifier "notify-send -u critical -t 10000 -- 'locking screen in 30 seconds'" &
#pywal
#feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
#$HOME/.config/wpg/wp_init.sh
#panel
$HOME/.config/bin/tin2start &
#$HOME/.config/polybar/launch.sh &
exec  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
mpd &
#cky &
# killall zentile &
# sleep 0.5 && zentile & disown
fi
